
modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="mynethersdelight"
version="1.20.1-1.7.5"
displayName="My Nether's Delight"

# updateJSONURL=""
logoFile="logo.png"
logoBlur=false
credits="Mpustovoi, Unroman, ChuijkYahus, SlimeSB, RaymondBlaze, TCGhost, Sarinsa, Umpaz, SoyTutta;"
authors="SoyTutta"
description="A nether expansion for the Farmer's Delight mod!"
itemIcon="mynethersdelight:nether_stove"
configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.mynethersdelight]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mynethersdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mynethersdelight]]
modId="farmersdelight"
mandatory=true
versionRange="[1.2.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.mynethersdelight]]
modId="miners_delight"
mandatory=false
versionRange="[1.2.3,)"
ordering="AFTER"
side="BOTH"